# $$$$$$$$\  $$$$$$\  $$$$$$$$\ $$$$$$$$\ $$\       $$\       
# \____$$  |$$  __$$\ $$  _____|$$  _____|$$ |      $$ |      
#     $$  / $$ /  \__|$$ |      $$ |      $$ |      $$ |      
#    $$  /  \$$$$$$\  $$$$$\    $$$$$\    $$ |      $$ |      
#   $$  /    \____$$\ $$  __|   $$  __|   $$ |      $$ |      
#  $$  /    $$\   $$ |$$ |      $$ |      $$ |      $$ |      
# $$$$$$$$\ \$$$$$$  |$$ |      $$$$$$$$\ $$$$$$$$\ $$$$$$$$\ 
# \________| \______/ \__|      \________|\________|\________|
flight_permission: "allow.fly"
flight_kick_reasons:
  no_permission: " r u using Cheat to fly??."
